RSA/Controllers/AvisoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RSA.Models;
using RSA.VM;
using System.IO;

namespace RSA.Controllers
{
    public class AvisoController : Controller
    {
        AvisoModel moduloModel = new AvisoModel();

        // GET: Aviso
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AllAviso(ServRSA.VMGridAvisoGet modelo)
        {
            ServRSA.VMTableOfVMAvisoi0e4Zjb6 model = moduloModel.CatalogoAviso(modelo);
            return Json(new { model }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Create(ServRSA.VMAviso model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {
                resp.result = moduloModel.RegistrarAviso(model);
                resp.success = true;
                resp.alerta = "Aviso registrado correctamente";
            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }

            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Details(int id)
        {
            ServRSA.VMAviso model = moduloModel.GetAviso(id);
            return Json(new { model }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Update(ServRSA.VMAviso model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {

                moduloModel.EditarAviso(model);
                resp.result = model;
                resp.success = true;
                resp.alerta = "Información actualizada correctamente";

            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }


            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Baja(int id)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {

                moduloModel.BajaAviso(id);
                resp.success = true;
                resp.alerta = "Información actualizada correctamente";

            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }


            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public string UploadImage(HttpPostedFileBase filepond, int id)
        {
            if (filepond.ContentLength <= 0)
            {
                return "Error mientras se cargaba el archivo";
            }
            else
            {
                string extension = filepond.FileName.Substring(filepond.FileName.LastIndexOf("."));
                string fileName = "aviso_"+ DateTime.Now.Ticks.ToString()+ "_" + id.ToString() + extension;
                //byte[] archivo = new byte[filepond.InputStream.Length];
                //filepond.InputStream.Read(archivo, 0, (int)filepond.InputStream.Length - 1);
                ServRSA.VMAviso model = moduloModel.GetAviso(id);
                if (System.IO.File.Exists(Server.MapPath("~/Images/avisos/" + model.NombreImagen)))
                {
                    System.IO.File.Delete(Server.MapPath("~/Images/avisos/" + model.NombreImagen));
                }
                    //model.ImagenBinary = archivo;
                model.NombreImagen = fileName; 
                this.Update(model);                            
                if(System.IO.File.Exists(Server.MapPath("~/Images/avisos/" + fileName)))
                {
                    System.IO.File.Delete(Server.MapPath("~/Images/avisos/" + fileName));
                }
                filepond.SaveAs(Server.MapPath("~/Images/avisos/"+fileName));
                return "Imagen cargada correctamente";
            }
        }

        [HttpPost]
        public JsonResult ListAviso(bool todos = true)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {
                resp.result = moduloModel.ListarAviso(todos);
                resp.success = true;
            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }

            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }
    }
}

RSA/Controllers/GaleriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using RSA.Models;
using RSA.ServRSA;
using RSA.VM;
using System.IO;
using System.Net;

namespace RSA.Controllers
{
    public class GaleriaController : Controller
    {
        GaleriaModel moduloModel = new GaleriaModel();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult AllGalerias(ServRSA.VMGridGaleriaGet modelo)
        {
            ServRSA.VMTableOfVMGaleriai0e4Zjb6 model = moduloModel.CatalogoGaleria(modelo);
            return Json(new { model }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Create(ServRSA.VMGaleria model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {
                resp.result = new GaleriaModel().RegistrarGaleria(model);
                resp.success = true;
                resp.alerta = "Galería registrada correctamente";
            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }

            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Details(int id)
        {
            ServRSA.VMGaleria model = new GaleriaModel().GetGaleria(id);
            return Json(new { model }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Update(ServRSA.VMGaleria model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {

                moduloModel.EditarGaleria(model);
                resp.success = true;
                resp.alerta = "Galería actualizada correctamente";

            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }


            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Delete(ServRSA.VMGaleria model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {
                new GaleriaModel().EliminarGaleria(model.IdGaleria);
                resp.success = true;
                resp.alerta = "Galería inactivada correctamente";
            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }

            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        #region Detalle Galerias 

        [HttpPost]
        public JsonResult AllImages(ServRSA.VMGridImagenGaleriaGet modelo)
        {
            
            ServRSA.VMTableOfVMImagenGaleriai0e4Zjb6 model = moduloModel.CatalogoImagenGaleria(modelo);
            return Json(new { model }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetImages(bool todas = true)
        {
            ServRSA.VMListImagenGaleria[] model = moduloModel.ObtenerImagesGaleria(todas);
            return Json(new { model }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public string UploadImage(HttpPostedFileBase filepond, int id)
        {
            if (filepond.ContentLength <= 0)
                throw new Exception("Error mientras se cargaba el archivo");
            //string extension = filepond.FileName.Substring(filepond.FileName.LastIndexOf(".", StringComparison.Ordinal));
            //byte[] archivo = new byte[filepond.InputStream.Length];
            //filepond.InputStream.Read(archivo, 0, (int)filepond.InputStream.Length - 1);
            //ServRSA.VMImagenGaleria model = moduloModel.GetImageGaleria(id);
            //model.BinaryImagen = archivo;
            //model.TipoImagen = filepond.ContentType;
            //this.UpdateImage(model);


            string extension = filepond.FileName.Substring(filepond.FileName.LastIndexOf("."));
            string fileName = "_" + id.ToString() + extension;
            byte[] archivo = new byte[filepond.InputStream.Length];
            filepond.InputStream.Read(archivo, 0, (int)filepond.InputStream.Length - 1);
            ServRSA.VMImagenGaleria model = moduloModel.GetImageGaleria(id);
            model.BinaryImagen = archivo;
            model.TipoImagen = extension; //filepond.ContentType;
            this.UpdateImage(model);
            if (!Directory.Exists(Server.MapPath("~/Images/galerias/_"+model.IdGaleria)))
            {
                Directory.CreateDirectory(Server.MapPath("~/Images/galerias/_" + model.IdGaleria));
            }
            filepond.SaveAs(Server.MapPath("~/Images/galerias/_" + model.IdGaleria+"/" + fileName));
            

            return "Imagen cargada correctamente";
        }

        [HttpPost]
        public JsonResult CreateImage(ServRSA.VMImagenGaleria model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {
                //Por ahora el usuario se coloca fijo
                model.IdUsuarioRegistra = 10001;
                resp.result = new GaleriaModel().RegistrarImageGaleria(model);
                resp.success = true;
                resp.alerta = "Imagen registrada correctamente";
            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }

            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult UpdateImage(ServRSA.VMImagenGaleria model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {

                moduloModel.ActualizarImageGaleria(model);
                resp.success = true;
                resp.alerta = "Imagen actualizada correctamente";

            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }


            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteImage(VMImagenGaleria imgGaleria)
        {

            RespuestaModel resp = new RespuestaModel();
            try
            {
                new GaleriaModel().EliminarImageGaleria(imgGaleria.IdImagen);
                if (Directory.Exists(Server.MapPath("~/Images/galerias/_" + imgGaleria.IdGaleria)))
                {
                    string fileName = "_" + imgGaleria.IdImagen + imgGaleria.TipoImagen;
                    string filenamecomplete = Server.MapPath("~/Images/galerias/_" + imgGaleria.IdGaleria + "/" + fileName);
                    if (System.IO.File.Exists(filenamecomplete))
                    {
                        System.IO.File.Delete(filenamecomplete);
                    }
                }
                resp.success = true;
                resp.alerta = "Imagen eliminada correctamente";
            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }

            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult InactivateImage(ServRSA.VMImagenGaleria model)
        {
            RespuestaModel resp = new RespuestaModel();
            try
            {
                new GaleriaModel().BajaImageGaleria(model.IdImagen);
                resp.success = true;
                resp.alerta = "Imagen inactivada correctamente";
            }
            catch (Exception ex)
            {
                resp.success = false;
                resp.mensaje = ex.Message;
            }

            return Json(new { model = resp }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DetailsImage(int id)
        {
            ServRSA.VMImagenGaleria model = new GaleriaModel().GetImageGaleria(id);

            // Crea un nuevo modelo solo para enviar el codigo bynario en base 64,
            // se podria hacer desde el cliente con JS, pero al ser imagenes cargaria mucho el motor del explorador.
            return Json(new { model = new {
                BinaryImagen = Convert.ToBase64String(  model.BinaryImagen),
                IdImagen = model.IdImagen,
                TipoImagen = model.TipoImagen
            } }, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

RSA/Views/Shared/_BannersFV.cshtml
<!-- Modal Aviso Primera Visita-->
<div class="modal fade" id="banners_home" tabindex="-1" role="dialog" aria-hidden="true">

    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">

                <div v-if="banners.length > 1" id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="index" v-for="(item, index) in banners" v-bind:class="active(index,'')"></li>
                    </ol>
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div v-bind:class="active(index,'item')" v-for="(item, index) in banners">
                            <img v-bind:src="'@Href("~/Images/home/index/banners/_")'+item.IdBanner+(item.TipoImagen==null?'.png':item.TipoImagen)" />
                        </div><!-- End .item -->
                    </div><!-- End .carousel-inner -->
                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev"><i class="fa fa-angle-left"></i></a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next"><i class="fa fa-angle-right"></i></a>
                </div><!-- End .carousel -->
                <div v-else-if="banners.length === 1">
                    <img v-for="(item, index) in banners" v-bind:src="'@Href("~/Images/home/index/banners/_")'+item.IdBanner+(item.TipoImagen==null?'.png':item.TipoImagen)" style="max-width: 100%; max-height: 100%;" alt="" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-black" data-dismiss="modal">CERRAR</button>
            </div>
        </div>
    </div>

</div><!-- End .Aviso Primera Visita -->

RSA/Views/Shared/_FootGeneral.cshtml
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="widget about-widget">
                    <img src="@Href("~/Images/logo_rsa.png")"  alt="Red Social Azteca">
                    <hr>
                    <p>"Una red de apoyo para quienes más lo necesitan, porque ayudar, es cuestión de voluntad"</p>
                </div><!-- End .widget -->
            </div><!-- End .col-md-5 -->
            <div class="col-md-7 col-md-offset-1">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="widget">

                            <h4 class="widget-title">Centros de Acopio</h4>
                            <h6 class="widget-title small">Internos</h6>
                            <ul class="fa-ul">
                                <li><a href="#" title="Periférico Sur #4121 Col. Tlalpan, Fuentes del Pedregal, C.P. 14141, CDMX"><i class="fa-li fa fa-chain"></i>TV Azteca</a></li>
                                <li><a href="#" title="Insurgentes Sur #3579, Col. Tlalpan, La Joya, C.P. 14000, CDMX"><i class="fa-li fa fa-chain"></i>Elektra</a></li>
                                <li><a href="#" title="Vereda 80, Col. Jardines del Pedregal, C.P. 01900, CDMX"><i class="fa-li fa fa-chain"></i>Fundación Azteca</a></li>
                                <li><a href="#" title="Periférico Sur 4277, Jardines en la Montaña, 14210 CDMX"><i class="fa-li fa fa-chain"></i>Italika</a></li>
                                <li><a href="#" title="Av. Insurgentes Sur #3155, Col. Insurgentes Cuicuilco, C.P. 04530  CDMX"><i class="fa-li fa fa-chain"></i>Banco Azteca</a></li>
                                <li><a href="#" title="Periférico Sur # 4121 Col Fuentes del Pedregal C.P. 14141 CDMX"><i class="fa-li fa fa-chain"></i>Total Play</a></li>

                                <li><a href="#" title="Montes Urales # 450 Lomas de Chapultepec V Sección C.P. 11000 CDMX"><i class="fa-li fa fa-chain"></i>Montes Urales</a></li>
                            </ul>
                            <h6 class="widget-title small">Externos</h6>
                            <ul class="fa-ul">
                                <li><a href="#"><i class="fa-li fa fa-chain"></i>Sportium</a></li>
                                <li><a href="#"><i class="fa-li fa fa-chain"></i>Otros...</a></li>
                            </ul>
                        </div>
                    </div><!-- End .col-sm-6 -->
                    <div class="col-sm-4">
                        <div class="widget">
                            <h4 class="widget-title">Directorio</h4>
                            <ul class="fa-ul">
                                <li><a href="#"><i class="fa-li fa fa-chain"></i>Red de Organizaciones Civiles</a></li>
                            </ul>
                            <h4 class="widget-title">Contacto</h4>
                            <ul class="fa-ul">
                                <li>
                                    <a href="#">
                                        <i class="fa-li fa fa-map"></i>Vereda No. 80<br />Col. Jardines del Pedregal <br />
                                        C.P. 01900 <br />
                                        México, D.F.
                                    </a>

                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa-li fa fa-phone"></i>(55) 1720 4930
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa-li fa fa-envelope"></i>redsocial@tvazteca.com.mx
                                    </a>
                                </li>
                            </ul>


                        </div><!-- End .widget -->
                    </div><!-- End .col-sm-3 -->
                    <div class="col-sm-4">
                        <div class="widget">
                            <h4 class="widget-title">Aviso de Privacidad</h4>
                            <ul class="fa-ul">
                                <li><a href="#"><i class="fa-li fa fa-unlock-alt"></i>Aviso Legal/Politica de Privacidad</a></li>
                            </ul>
                            <h4 class="widget-title">S&iacute;guenos en</h4>
                            <ul class="fa-ul">
                                <li><a href="#"><i class="fa-li fa fa-facebook"></i>Facebook</a></li>
                                <li><a href="#"><i class="fa-li fa fa-instagram"></i>Instagram</a></li>
                                <li><a href="#"><i class="fa-li fa fa-twitter"></i>Twitter</a></li>
                                <li><a href="#"><i class="fa-li fa fa-youtube"></i>Youtube</a></li>
                            </ul>
                        </div><!-- End .widget -->
                    </div><!-- End .col-sm-3 -->
                </div><!-- End .row -->
            </div><!-- End .col-md-6 -->
        </div><!-- End .row -->
    </div><!-- End .container -->
    <div class="footer-bottom">
        <div class="container">
            <div class="footer-right">
                <ul class="footer-menu">
                    <li class="active"><a class="ir_a" href="#wrapper">Inicio</a></li>
                    <li><a href="#">Nosotros</a></li>
                    <li><a href="#">Embajador</a></li>
                    <li><a href="#">Nuestros programas</a></li>
                    <!--<li><a href="#nuestras_causas" class="ir_a">Nuestras causas</a></li>-->
                    <!--<li><a href="#">Contacto</a></li>-->
                </ul>
            </div><!-- End .footer-right -->
            <p class="copyright">Derechos reservados por Red Social Azteca 2018 &copy;.</p>
        </div><!-- End .container -->
    </div><!-- End .footer-bottom -->
</footer><!-- End .footer -->

RSA/Views/Shared/_HeaderPublic.cshtml
<header class="header sticky-header">
    <div class="header-inner">
        <div class="container">
            <a href="index.html" class="site-logo" title="Red Social. FAZ">
                <img src="@Href("~/Images/logo_faz.png")" alt="Red Social" class="faz">
                <!--<span class="sr-only">Red Social</span>-->
                <img src="@Href("~/Images/logo_rsa.png")" alt="Red Social" class="rsa">
                <!--<span class="sr-only">Red Social</span>-->
            </a>
            <div class="header-info-boxes">

                <div class="header-info-box">
                    <i class="fa fa-thumbs-up success"></i>
                    <div class="info-box-title">347,588</div>
                    <p>visitas</p>
                </div><!-- End .header-info-box -->

                @Html.Partial("_Login")
            </div><!-- End header-info-boxes -->
        </div><!-- End .container -->
    </div><!-- End .header-inner -->
    <div class="header-bottom">
        @Html.Partial("_Menu")

    </div><!-- End .header-bottom -->
</header><!-- End .header -->

RSA/Views/Shared/_HeaderSticky.cshtml
<header class="header sticky-header">
    <div class="header-inner">
        <div class="container">
            <a href="../../index.html" class="site-logo" title="Red Social. FAZ">
                <img src="../../images/logo_faz.png" alt="Red Social" class="faz">
                <!--<span class="sr-only">Red Social</span>-->
                <img src="../../images/logo_rsa.png" alt="Red Social" class="rsa">
                <!--<span class="sr-only">Red Social</span>-->
            </a>
            <div class="dropdown header-dropdown cart-dropdown">
                <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="">
                        <i class="glyphicon glyphicon glyphicon-user"></i>
                    </span>
                </a>
            </div><!-- End .user -->

        </div><!-- End .container -->
    </div><!-- End .header-inner -->
    <div class="header-bottom">
        <div class="container">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav-container"
                    aria-expanded="false">
                <span class="toggle-text">Menu</span>
                <span class="toggle-wrapper">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </span>
            </button>
            <div class="collapse navbar-collapse" id="main-nav-container">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="../../index.html" class="dropdown-toggle" role="button" aria-expanded="false">Inicio</a>
                    </li>
                    <li class="dropdown">
                        <a href="../galerias/admin_galerias.html" class="dropdown-toggle" role="button" aria-expanded="false">Galerías</a>
                    </li>
                    <li class="dropdown active">
                        <a href="../main_slider/main_slider.html" class="dropdown-toggle" role="button" aria-expanded="false">Slider </a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- End .container -->
    </div><!-- End .header-bottom -->
</header><!-- End .header -->

RSA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Red Social. Fundación Azteca</title>
    <!-- Google Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700%7COpen+Sans:300,300i,400,400i,600,600i,700,800" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/theme-faz")

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="@Href("~/Images/icons/favicon.png")">

    <script>
        var baseUrl = function (url) {
            return '@Href("~/")'+url;
        }
    </script>
    @*@Scripts.Render("~/bundles/jquery")*@
    <!-- GALERIA simplelightbox  -->
    @*<link href="js/plugins/simple-lightbox/simplelightbox.min.css" rel="stylesheet" />*@

    <!-- Modernizr -->
    @Scripts.Render("~/bundles/modernizr")


    @RenderSection("header", required: false)
</head>
<body>
    @RenderBody()

    <!-- Modal Aviso Primera Visita-->
    @Html.Partial("_BannersFV")

    @* @Scripts.Render("~/bundles/bootstrap")*@

    @Scripts.Render("~/bundles/plugin")
    @Scripts.Render("~/bundles/scriptsvue-layout")



    @RenderSection("scripts", required: false)
</body>
</html>

RSA/Views/Shared/_Menu.cshtml
<div class="container">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav-container" aria-expanded="false">
        <span class="toggle-text">Menu</span>
        <span class="toggle-wrapper">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </span>
    </button>
    <div class="collapse navbar-collapse" id="main-nav-container">
        <ul class="nav navbar-nav">
            <li class="dropdown active">
                <a href='@Url.Action("Index", "Home")' class="dropdown-toggle" role="button" aria-expanded="false">Inicio</a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Nosotros<span class="angle"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="~/Nosotros/quienes-somos">¿Quiénes somos?</a></li>
                    <li><a href="~/Nosotros/historia">Historia</a></li>
                    <li><a href="~/Nosotros/objetivos">Objetivos</a></li>
                    <li><a href="~/Nosotros/pilares">Pilares</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Vinculacion<span class="angle"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Premio</a></li>

                </ul>
            </li>
            <!--<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Nuestros programas<span class="angle"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="donativos.html">Donativos</a></li>
                    <li><a href="comite_donativos.html">¿Qué es el Comité de Donativos?</a></li>
                    <li><a href="como_donar.html">¿Qué y como puedo donar?</a></li>
                    <li><a href="realizar_donativo.html">¿Deseas realizar un donativo?</a></li>
                    <li><a href="necesitas_donativo.html">¿Necesitas un donativo?</a></li>
                    <li><a href="no_dona_rs.html">¿Qué no dona Red Social?</a></li>
                </ul>
            </li>-->
            <!--<li class="dropdown">
                <a href="#nuestras_causas" class="ir_a dropdown-toggle" role="button" aria-expanded="false">Nuestras causas <span class="tip soon">Ver</span></a>
            </li>-->
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Voluntariado<span class="tip new"> <i class="fa fa-thumbs-o-up custom"></i> </span> <span class="angle"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="~/Voluntariado/conoce-mas">Conoce más</a></li>
                    <li><a href="~/Voluntariado/requisitos">Requisistos</a></li>
                    <li><a href="~/Voluntariado/registro">Registro</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Embajador<span class="angle"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="~/Embajador/perfil">Perfil</a></li>
                            <li><a href="~/Embajador/nuestro-embajador">Nuestro Embajador</a></li>
                            <li><a href="~/Embajador/actividades">Actividades</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#nuestras_causas" class="ir_a dropdown-toggle" role="button" aria-expanded="false">Donativos <span class="tip hot"><i class="fa fa-heart"></i></span></a>
            </li>
            <li class="dropdown pull-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Administrador<span class="tip new"> Admin </span> <span class="angle"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href='@Url.Action("Index", "Galeria")'>Galeria</a></li>
                    <li><a href='@Url.Action("Index", "Aviso")'>Aviso</a></li>
                </ul>
            </li>
        </ul>
    </div><!-- /.navbar-collapse -->
</div><!-- End .container -->